[package]
name = "bva"
version = "0.1.0"
authors = ["Charles Hubain <github@haxelion.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]

rand = "0.7"