name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check code with rustfmt and clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check code with rustfmt
        run: cargo fmt --check
      - name: Check code with clippy
        run: cargo clippy
  test:
    name: Build and run tests
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build library
        run: cargo build --verbose
      - name: Run tests
        run: RUST_BACKTRACE=1 cargo test --verbose
  coverage:
    name: coverage
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --verbose --all-features --engine llvm --out xml
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
