name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check code with rustfmt and clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check code with rustfmt
      run: cargo fmt --check
    - name: Check code with clippy
      run: cargo clippy
  test:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build library
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
